// file use: game data for WYR, Trivia, Two Truths, Most Likely To, Quick Draw

export const WOULD_YOU_RATHER = [
  { a: "Have unlimited money but no friends", b: "Have amazing friends but always be broke" },
  { a: "Be able to fly", b: "Be able to be invisible" },
  { a: "Know how you die", b: "Know when you die" },
  { a: "Live without music", b: "Live without social media" },
  { a: "Be the funniest person in the room", b: "Be the smartest person in the room" },
  { a: "Only eat your favourite food forever", b: "Never eat your favourite food again" },
  { a: "Have a rewind button for your life", b: "Have a pause button for your life" },
  { a: "Be famous but unhappy", b: "Be unknown but happy" },
  { a: "Speak every language", b: "Play every instrument" },
  { a: "Always be 10 minutes late", b: "Always be 20 minutes early" },
  { a: "Fight 100 duck-sized horses", b: "Fight 1 horse-sized duck" },
  { a: "Have no WiFi for a month", b: "Have no sleep for a week" },
  { a: "Live in the past", b: "Live in the future" },
  { a: "Be able to read minds", b: "Be able to predict the future" },
  { a: "Give up your phone for a year", b: "Give up junk food for a year" },
  { a: "Always have to sing instead of speak", b: "Always have to dance instead of walk" },
  { a: "Only be able to whisper", b: "Only be able to shout" },
  { a: "Have unlimited battery on all devices", b: "Have unlimited data forever" },
  { a: "Go back to being 5 with your current knowledge", b: "Jump 20 years into the future" },
  { a: "Be a superhero with a useless power", b: "Be a villain with an amazing power" },
];

export const TRIVIA = [
  { q: "What is the capital of Australia?", options: ["Sydney","Melbourne","Canberra","Brisbane"], answer: 2 },
  { q: "How many sides does a hexagon have?", options: ["5","6","7","8"], answer: 1 },
  { q: "What gas do plants absorb?", options: ["Oxygen","Nitrogen","Carbon Dioxide","Hydrogen"], answer: 2 },
  { q: "Who painted the Mona Lisa?", options: ["Michelangelo","Raphael","Leonardo da Vinci","Donatello"], answer: 2 },
  { q: "Smallest planet in our solar system?", options: ["Mars","Mercury","Venus","Pluto"], answer: 1 },
  { q: "How many bones in the adult human body?", options: ["196","206","216","226"], answer: 1 },
  { q: "What year did the first iPhone launch?", options: ["2005","2006","2007","2008"], answer: 2 },
  { q: "Which country invented pizza?", options: ["France","Greece","USA","Italy"], answer: 3 },
  { q: "Chemical symbol for gold?", options: ["Go","Gd","Au","Ag"], answer: 2 },
  { q: "How many continents on Earth?", options: ["5","6","7","8"], answer: 2 },
  { q: "Longest river in the world?", options: ["Amazon","Nile","Yangtze","Mississippi"], answer: 1 },
  { q: "Known as the Red Planet?", options: ["Venus","Jupiter","Saturn","Mars"], answer: 3 },
  { q: "What is 15% of 200?", options: ["25","30","35","40"], answer: 1 },
  { q: "Who wrote Harry Potter?", options: ["Tolkien","C.S. Lewis","J.K. Rowling","Roald Dahl"], answer: 2 },
  { q: "Fastest land animal?", options: ["Lion","Cheetah","Horse","Greyhound"], answer: 1 },
  { q: "Strings on a standard guitar?", options: ["4","5","6","7"], answer: 2 },
  { q: "Most native speakers?", options: ["English","Spanish","Hindi","Mandarin"], answer: 3 },
  { q: "Hardest natural substance?", options: ["Gold","Iron","Diamond","Quartz"], answer: 2 },
  { q: "Largest ocean?", options: ["Atlantic","Indian","Arctic","Pacific"], answer: 3 },
  { q: "Powerhouse of the cell?", options: ["Nucleus","Ribosome","Mitochondria","Golgi"], answer: 2 },
];

export const MOST_LIKELY_TO = [
  "become a millionaire",
  "accidentally send a text to the wrong person",
  "become famous on social media",
  "show up late to their own wedding",
  "survive a zombie apocalypse",
  "eat the most at a buffet",
  "become a CEO",
  "forget their own birthday",
  "move to another country",
  "win a reality TV show",
  "stay up until 5am for no reason",
  "become a professor",
  "cry at a movie",
  "get lost in a familiar place",
  "invent something world-changing",
  "forget someone's name immediately after meeting them",
  "be the last one standing at a party",
  "start a business that actually works",
  "go viral for something embarrassing",
  "still be friends with everyone here in 10 years",
];

export const TWO_TRUTHS_PROMPTS = [
  "Share 2 truths and 1 lie about your yourself",
  "Share 2 truths and 1 lie about places you've been",
  "Share 2 truths and 1 lie about your skills",
  "Share 2 truths and 1 lie about your fears",
  "Share 2 truths and 1 lie about things you've eaten",
  "Share 2 truths and 1 lie about your achievements",
  "Share 2 truths and 1 lie about your personality",
  "Share 2 truths and 1 lie about your hobbies",
];

export const QUICK_DRAW_WORDS = [
  "Elephant","Rainbow","Pizza","Guitar","Volcano",
  "Astronaut","Submarine","Tornado","Lighthouse","Cactus",
  "Penguin","Rollercoaster","Thunderstorm","Treehouse","Compass",
  "Jellyfish","Skateboard","Campfire","Telescope","Hammock",
  "Waterfall","Boomerang","Quicksand","Igloo","Trampoline",
  "Avalanche","Binoculars","Catapult","Dominos","Escalator",
];
