export const WOULD_YOU_RATHER = [
  { a: "Have unlimited money but no friends", b: "Have amazing friends but always be broke" },
  { a: "Be able to fly", b: "Be able to be invisible" },
  { a: "Know how you die", b: "Know when you die" },
  { a: "Live without music", b: "Live without social media" },
  { a: "Be the funniest person in the room", b: "Be the smartest person in the room" },
  { a: "Only eat your favourite food forever", b: "Never eat your favourite food again" },
  { a: "Have a rewind button for your life", b: "Have a pause button for your life" },
  { a: "Be famous but unhappy", b: "Be unknown but happy" },
  { a: "Speak every language", b: "Play every instrument" },
  { a: "Always be 10 minutes late", b: "Always be 20 minutes early" },
  { a: "Fight 100 duck-sized horses", b: "Fight 1 horse-sized duck" },
  { a: "Have no WiFi for a month", b: "Have no sleep for a week" },
  { a: "Live in the past", b: "Live in the future" },
  { a: "Be able to read minds", b: "Be able to predict the future" },
  { a: "Give up your phone for a year", b: "Give up junk food for a year" },
  { a: "Always have to sing instead of speak", b: "Always have to dance instead of walk" },
  { a: "Be a superhero with a useless power", b: "Be a villain with an amazing power" },
  { a: "Only be able to whisper", b: "Only be able to shout" },
  { a: "Have unlimited battery life on all devices", b: "Have unlimited data forever" },
  { a: "Go back to being 5 years old with your current knowledge", b: "Jump 20 years into the future" },
];

export const TRIVIA = [
  { q: "What is the capital of Australia?", options: ["Sydney", "Melbourne", "Canberra", "Brisbane"], answer: 2 },
  { q: "How many sides does a hexagon have?", options: ["5", "6", "7", "8"], answer: 1 },
  { q: "What gas do plants absorb from the atmosphere?", options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"], answer: 2 },
  { q: "Who painted the Mona Lisa?", options: ["Michelangelo", "Raphael", "Leonardo da Vinci", "Donatello"], answer: 2 },
  { q: "What is the smallest planet in our solar system?", options: ["Mars", "Mercury", "Venus", "Pluto"], answer: 1 },
  { q: "How many bones are in the adult human body?", options: ["196", "206", "216", "226"], answer: 1 },
  { q: "What year did the first iPhone launch?", options: ["2005", "2006", "2007", "2008"], answer: 2 },
  { q: "Which country invented pizza?", options: ["France", "Greece", "USA", "Italy"], answer: 3 },
  { q: "What is the chemical symbol for gold?", options: ["Go", "Gd", "Au", "Ag"], answer: 2 },
  { q: "How many continents are there on Earth?", options: ["5", "6", "7", "8"], answer: 2 },
  { q: "What is the longest river in the world?", options: ["Amazon", "Nile", "Yangtze", "Mississippi"], answer: 1 },
  { q: "Which planet is known as the Red Planet?", options: ["Venus", "Jupiter", "Saturn", "Mars"], answer: 3 },
  { q: "What is 15% of 200?", options: ["25", "30", "35", "40"], answer: 1 },
  { q: "Who wrote Harry Potter?", options: ["Tolkien", "C.S. Lewis", "J.K. Rowling", "Roald Dahl"], answer: 2 },
  { q: "What is the fastest land animal?", options: ["Lion", "Cheetah", "Horse", "Greyhound"], answer: 1 },
  { q: "How many strings does a standard guitar have?", options: ["4", "5", "6", "7"], answer: 2 },
  { q: "What language has the most native speakers?", options: ["English", "Spanish", "Hindi", "Mandarin"], answer: 3 },
  { q: "What is the hardest natural substance on Earth?", options: ["Gold", "Iron", "Diamond", "Quartz"], answer: 2 },
  { q: "Which ocean is the largest?", options: ["Atlantic", "Indian", "Arctic", "Pacific"], answer: 3 },
  { q: "What is the powerhouse of the cell?", options: ["Nucleus", "Ribosome", "Mitochondria", "Golgi"], answer: 2 },
];
